apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies
spec:
  selector:
    matchLabels:
      app: movies
  template:
    metadata:
      labels:
        app: movies
    spec:
      containers:
      - name: moveis
        image: alvaronascimentoapn/rotten-potatoes:v1
        ports:
          - containerPort: 5000
        env:
          - name: MONGO_DB
            value: admin
          - name: MONGODB_HOST
            value: mongodb
          - name: MONGODB_PORT
            value: "27017"
          - name: MONGODB_USERNAME
            value: mongouser
          - name: MONGODB_PASSWORD
            value: mongopwd
---
apiVersion: v1
kind: Service
metadata:
    name: movies-services
spec: 
    selector:
        app: movies
    ports:
      - port: 80
        targetPort: 5000
        nodePort: 30000
    type: NodePort